config/routes.rb
PromrWeb::Application.routes.draw do

  devise_scope :users do
    get '/users/sign_in', to: redirect('/'), :as => :new_user_session
  end

  devise_for :users,
             controllers: { :omniauth_callbacks => "users/omniauth_callbacks" },
             skip: [:registrations, :passwords, :unlocks]

  controller :home do
    get '/home', action: :index
    get '/contact_us', action: :contact_us, as: :contact_us
    get '/terms', action: :terms, as: :terms
  end

  unauthenticated :user do
    root to: redirect('/home')
  end

  authenticated :user do
    root controller: :user_dashboard, action: :promr_box
  end

  controller :user_dashboard do
    get '/search', action: :search, as: :search
    get '/friends', action: :friends, as: :friends
    get '/facebook_friends', action: :facebook_friends, as: :facebook_friends
  end

  controller :user_profile do
    get '/me/edit', action: :edit, as: :edit_user_profile
    put '/me', action: :update, as: :update_user_profile
    get '/me', action: :show_me, as: :my_profile

    get '/u/:id', action: :show, as: :user_profile

    get '/u/:id/invite_friend', action: :invite_friend, as: :invite_friend
    get '/u/:id/approve_friend', action: :approve_friend, as: :approve_friend
    get '/u/:id/cancel_invite', action: :cancel_invite, as: :cancel_invite
    get '/u/:id/remove_friend', action: :remove_friend, as: :remove_friend
    get '/u/:id/block_friend', action: :block_friend, as: :block_friend
    get '/u/:id/unblock_friend', action: :unblock_friend, as: :unblock_friend
  end

  resources :coupons, only: [:index, :show]

  resources :stores, only: [:index]

  resources :offers, only: [:show] do
    put 'new_coupon', action: :new_coupon, as: :new_coupon
  end

  devise_for :store_users

  get '/store_dashboard', action: :index, controller: :store_dashboard, as: :store_user_root

  namespace :store_dashboard do
    post '/change_image', action: :change_image
    resources :offers do
      get '/activate', action: :activate
      get '/deactivate', action: :deactivate
    end
    resources :coupons do
      get '/buy', action: :buy, :on => :collection
    end

    post '/use_coupon', action: :use_coupon
    get '/use_coupon' => redirect('/store_dashboard/')
    get '/profile', action: :profile
    get '/help', action: :profile
  end

  devise_for :admin_users

  get '/admin_dashboard', action: :index, controller: :admin_dashboard, as: :admin_user_root

  namespace :admin_dashboard do
    resources :stores
    resources :offers
    resources :store_users
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  devise :database_authenticatable,
        :rememberable, :trackable, :validatable

  attr_accessible :name, :email, :password, :password_confirmation, :remember_me

  belongs_to :store
end

app/views/admin_users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <br/><%= link_to "Entrar", new_session_path(resource_name) %>
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <br/><%= link_to "Registrar", new_registration_path(resource_name) %>
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <br/><%= link_to "Esqueceu sua senha?", new_password_path(resource_name) %>
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <br/><%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %>
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <br/><%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %>
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <br/><%= link_to "Entrar como #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %>
  <% end -%>
<% end -%>