config/routes.rb
PromrWeb::Application.routes.draw do

  devise_scope :users do
    get '/users/sign_in', to: redirect('/'), :as => :new_user_session
  end

  devise_for :users,
             controllers: { :omniauth_callbacks => "users/omniauth_callbacks" },
             skip: [:registrations, :passwords, :unlocks]

  controller :home do
    get '/home', action: :index
    get '/contact_us', action: :contact_us, as: :contact_us
    get '/terms', action: :terms, as: :terms
  end

  unauthenticated :user do
    root to: redirect('/home')
  end

  authenticated :user do
    root controller: :user_dashboard, action: :promr_box
  end

  controller :user_dashboard do
    get '/search', action: :search, as: :search
    get '/friends', action: :friends, as: :friends
    get '/facebook_friends', action: :facebook_friends, as: :facebook_friends
  end

  controller :user_profile do
    get '/me/edit', action: :edit, as: :edit_user_profile
    put '/me', action: :update, as: :update_user_profile
    get '/me', action: :show_me, as: :my_profile

    get '/u/:id', action: :show, as: :user_profile

    get '/u/:id/invite_friend', action: :invite_friend, as: :invite_friend
    get '/u/:id/approve_friend', action: :approve_friend, as: :approve_friend
    get '/u/:id/cancel_invite', action: :cancel_invite, as: :cancel_invite
    get '/u/:id/remove_friend', action: :remove_friend, as: :remove_friend
    get '/u/:id/block_friend', action: :block_friend, as: :block_friend
    get '/u/:id/unblock_friend', action: :unblock_friend, as: :unblock_friend
  end

  resources :coupons, only: [:index, :show]

  resources :stores, only: [:index]

  resources :offers, only: [:show] do
    put 'new_coupon', action: :new_coupon, as: :new_coupon
  end

  devise_for :store_users

  get '/store_dashboard', action: :index, controller: :store_dashboard, as: :store_user_root

  namespace :store_dashboard do
    post '/change_image', action: :change_image
    resources :offers do
      get '/activate', action: :activate
      get '/deactivate', action: :deactivate
    end
    resources :coupons do
      get '/buy', action: :buy, :on => :collection
    end

    post '/use_coupon', action: :use_coupon
    get '/use_coupon' => redirect('/store_dashboard/')
    get '/profile', action: :profile
    get '/help', action: :profile
  end

  devise_for :admin_users

  get '/admin_dashboard', action: :index, controller: :admin_dashboard, as: :admin_user_root

  namespace :admin_dashboard do
    resources :stores
    resources :offers
    resources :store_users
  end

end

app/controllers/user_dashboard_controller.rb
class UserDashboardController < ApplicationController
  include UserDashboardControllersSharedBehavior

  def promr_box
    @offer_shares = current_user.offer_shares.limit(5)
  end

  def friends
    @friends = current_user.friends.preview_info.order_by_name
  end

  def search
    @search = params[:search]
    if @search.blank?
      errors << 'Digite pelo menos uma palavra a ser pesquisada'
      redirect_to root_path
    else
      @all_users = User.search(@search)
      @all_stores = Store.search(@search)
      @all_offers = Offer.search(@search)
    end
  end

end

app/views/user_dashboard/_my_top_badges.html.erb
<div class="box">
  <div class="box-cabecalho">
    <p class="titulo-box pull-left">Minhas Conquistas <span class="badge"><%= @top_badges.size %></span></p>
    <div class="clearfix"></div>
  </div>

  <% @top_badges.each do |badge| %>
    <div class="thumb-rede pull-left">
      <a title="<%= badge.title %>" href="#" class="tooltipo" data-placement="top" ></a>
      <%= render 'shared/framed_picture-small', image_url: badge.image_url %>
    </div>
  <% end %>

  <div class="clearfix"></div>

  <div class="box-footer">
    <p><a href="#" class="btn btn-primary btn-block disabled">Ver tudo</a></p>
  </div>

  <div class="clearfix"></div>
</div>

app/views/user_dashboard/_my_top_friends.html.erb
<div class="box">
  <div class="box-cabecalho">
    <p class="titulo-box pull-left">Minha Rede <span class="badge"><%= @top_friends.size %></span></p>
    <div class="clearfix"></div>
  </div>

  <% @top_friends.each do |friend| %>
    <div class="thumb-rede pull-left">
      <a title="<%= friend.name %>" href="<%= user_profile_path(friend.id) %>" class="tooltipo" data-placement="top"></a>
      <%= render 'shared/framed_picture-small', image_url: friend.image_url %>
    </div>
  <% end %>

  <div class="clearfix"></div>

  <div class="box-footer">
    <form class="navbar-search" action="">
      <p><input type="text" class="search-query" placeholder="Pesquisar amigos"></p>
    </form>
    <div class="clearfix"></div>
    <p><a href="<%= friends_path %>" class="btn btn-primary btn-block disabled">Ver tudo</a></p>
    <p><a href="#" class="btn btn-success btn-block">Convidar Amigos</a></p>
  </div>

  <div class="clearfix"></div>
</div>

app/views/user_dashboard/_my_top_network.html.erb
<div class="box">
  <div class="box-cabecalho">
    <p class="titulo-box pull-left">Minha Rede <span class="badge"><%= @top_friends.size %></span></p>
    <div class="clearfix"></div>
  </div>

  <% @top_friends.each do |friend| %>
    <div class="thumb-rede pull-left">
      <a title="<%= friend.name %>" href="<%= user_profile_path(friend.id) %>" class="tooltipo" data-placement="top"></a>
      <%= render 'shared/framed_picture-small', image_url: friend.image_url %>
    </div>
  <% end %>

  <div class="clearfix"></div>

  <div class="box-footer">
    <form class="navbar-search" action="">
      <p><input type="text" class="search-query" placeholder="Pesquisar amigos"></p>
    </form>
    <div class="clearfix"></div>
    <p><a href="<%= my_friends_path %>" class="btn btn-primary btn-block disabled">Ver tudo</a></p>
    <p><a href="#" class="btn btn-success btn-block">Convidar Amigos</a></p>
  </div>

  <div class="clearfix"></div>
</div>

app/views/user_dashboard/_user_information.html.erb
<div class="box">
  <div class="photo-phrame">
    <%= render 'shared/framed_picture-medium', image_url: current_user.image_url %>
  </div>

  <div id="dados-user">
    <p class="nome titulo-box"><%= current_user.name %></p>
    <p>
      <span><strong>Pontos:&nbsp;</strong></span><span class="badge">430 / 500</span>
      <span><strong>Nível:&nbsp;</strong></span><span class="badge">3</span>
    </p>

    <div id="karma" class="progress active progress-success">
      <div class="bar" style="width: 80%"></div>
    </div>

    <a href="<%= edit_user_profile_path %>" class="btn btn-block btn-warning">Editar Perfil</a>
  </div><!--/dados-user-->
</div><!--box-->

app/views/user_dashboard/facebook_friends.html.erb
<h1>Amigos do Facebook</h1>

<div>
<% @friends.each do |friend_hash| %>
  <% friend = OpenStruct.new(friend_hash) %>
  <div class="thumb-rede pull-left">
    <a href="<%= friend.profile_url %>" target="_blank"></a>
    <%= render 'shared/framed_picture-small', image_url: friend.pic_square %>

    <div>
      <p class="nome titulo-box"><%= friend.name %></p>
      <%= hidden_field_tag :friend_id, friend.uid %>
    </div>
  </div>
<% end %>
</div>

<div class="clearfix"></div>

app/views/user_dashboard/friends.html.erb
<% facebook_presenter = FacebookFriendsPresenter.new(current_user) %>
<h1>Meus Amigos</h1>

<div class="lista-amigos">
  <ul class="nav nav-tabs" id="friends_tabs">
    <li class="active"><a href="#promr_friends">Promr</a></li>
    <li><a href="#facebook_friends">Facebook</a></li>
  </ul>

  <div class="tab-content">
    <div class="tab-pane active" id="promr_friends">
      <% @friends.each do |friend| %>
        <div class="friend-card pull-left">
          <div class="friend-photo">
            <img src="<%= friend.image_url %>" width="172" height="172" alt="Nome do Amigo" title="Nome do Amigo">
          </div>
          <div class="friend-details">
            <p class="friend-name"><a href="#">Francisco Marley Dieb</a></p>
          </div><!--/friends-details-->
        </div><!--/friend-card-->
      <% end %>
    </div>

    <div class="tab-pane" id="facebook_friends">
      <p class="subtitulo-busca">Adicionar amigos que já fazem parte do Promr</p>

      <% facebook_presenter.friends_signed_up.each do |friend| %>
        <div class="friend-card pull-left">
          <div class="friend-photo">
            <img src="<%= friend.promr_user.image_url %>" width="172" height="172" alt="Nome do Amigo" title="Nome do Amigo">
          </div>
          <div class="friend-details">
            <p class="friend-name">
              <a href="<%= user_profile_path(friend.promr_user.id) %>"><%= friend.promr_user.name %></a>
            </p>
            <a href="#" class="btn btn-block btn-primary">
              <i class="icon-plus icon-white"></i> Adicionar
            </a>
          </div><!--/friends-details-->
        </div><!--/friend-card-->
      <% end %>

      <div class="clearfix"></div>
      <p class="subtitulo-busca">Convidar amigos para o Promr</p>

      <% facebook_presenter.friends_not_signed_up.each do |friend| %>
        <div class="friend-card pull-left">
          <div class="friend-photo">
            <img src="<%= friend.pic_square %>" width="172" height="172" alt="Nome do Amigo" title="Nome do Amigo">
          </div>
          <div class="friend-details">
            <p class="friend-name">
              <a href="<%= friend.profile_url %>"><%= friend.name %></a>
            </p>
            <a href="#" class="btn btn-block btn-success">
              <i class="icon-envelope icon-white"></i> Convidar
            </a>
          </div><!--/friends-details-->
        </div><!--/friend-card-->
      <% end %>
    </div>
  </div>

  <div class="clearfix"></div>
</div>

<div class="clearfix"></div>
<script type="text/javascript">
  $('#friends_tabs a').on('click', function (e) {
    e.preventDefault();
    $(this).tab('show');
  });

</script>

app/views/user_dashboard/promr_box.html.erb
<h1>Promr Box</h1>
<h2>Cupons enviados por seus amigos</h2>

<div class="accordion" id="accordion-promrbox">

  <% @offer_shares.each do |share| %>

    <div class="accordion-group">
      <div class="accordion-heading">
        <a class="accordion-toggle btn pull-left" data-toggle="collapse" data-parent="#accordion-promrbox" href="#linha_<%= share.id %>"><i class="icon-plus"></i></a>
        <span class="pull-left"><strong>Enviado por:&nbsp;</strong>
          <a href="<%= user_profile_path(share.from_user.id) %>"><%= share.from_user.name %></a>
        </span>
        <span class="pull-left"><strong>Loja:&nbsp;</strong>
          <a href="#"><%= share.offer.store.name %></a>
        </span>
        <span class="pull-left"><strong>Local:&nbsp;</strong>
          <a href="#"><%= share.offer.store.mall.name %></a>
        </span>

        <a title="Ignorar" href="#" class="btn btn-danger btn-mini pull-right tooltipo" data-placement="left">
          <i class="icon-remove icon-white"></i>
        </a>
        <div class="clearfix"></div>
      </div>

      <!--para deixar aberto, use a classe 'in' após o collapse-->
      <div id="linha_<%= share.id %>" class="accordion-body collapse <%= share.unread ? 'in' : '' %>">
        <div class="accordion-inner">
          <div class="container-fluid">
            <div class="row-fluid">
              <div class="span2">
                <div class="logo-loja">
                  <a href="#"><img src="<%= share.offer.store.image.url %>" alt="Logo da Loja" title="Loja"/></a>
                </div><!--/logo-loja-->
                <div class="pontuacao-loja">
                  <p><span class="starred">&#9733;</span><span class="starred">&#9733;</span><span class="starred">&#9733;</span><span class="starred">&#9733;</span><span>&#9734;</span>
                  </p>
                </div><!--/pontuacao-loja-->
              </div><!--/span2-->

              <div class="span8">
                <div class="oferta-description">
                  <h3><a href="#"><%= share.offer.title %></a></h3>
                  <p class="description"><%= simple_format(share.offer.description) %></p>
                </div><!--/oferta-description-->

                <div class="ofertas-botoes">
                  <a href="#" class="btn btn-success"><i class="icon-thumbs-up icon-white"></i>&nbsp;Pegar</a>
                  <a href="#" class="btn btn-info"><i class="icon-info-sign icon-white"></i>&nbsp;Informações</a>
                  <a href="#" class="btn btn-warning"><i class="icon-camera icon-white"></i>&nbsp;Fotos</a>
                  <span class="label label-important"><strong>Válido até</strong> <%= share.offer.end_time %></span>
                </div><!--/ofertas-botoes-->
              </div><!--/span8-->

              <div class="span2">
                <div class="valor-oferta">
                  <% if share.offer.prices_defined? %>
                    <p><span><strong>De:&nbsp;</strong></span><%= currency(share.offer.original_price) %></p>
                    <p><strong>Por:</strong></p>
                    <p class="preco"><strong><%= currency(share.offer.current_price) %></strong></p>
                  <% else %>
                    <p class="preco"><strong><%= percentage(share.offer.discount) %></strong></p>
                  <% end %>
                </div>
              </div><!--/span2-->
            </div><!--/row-fluid *oferta-->
          </div><!--/container-fluid *oferta-->
        </div><!--/accordion-inner-->
      </div><!--/accordion-body-->
    </div><!-- accordion-->
  <% end %>
</div>

app/views/user_dashboard/search.html.erb
<h1>Resultados da Busca</h1>
<h2>Resultados para: "<%= @search %>"</h2>

<div id="resultado-busca">
  <div class="bloco-resultado-busca">
    <p class="subtitulo-busca">Pessoas</p>
    <span class="label label-important"><%= @all_users.size %></span> Resultados para <strong>"<%= @search %>"</strong>

    <div class="resultado">
      <% @all_users.each do |user| %>
        <div class="row-fluid">
          <div class="thumb-medio span2">
            <a title="<%= user.name %>" href="<%= user_profile_path(user.id) %>" class="tooltipo" data-placement="top"></a>
            <%= render 'shared/framed_picture-small', image_url: user.image_url %>
          </div>

          <div class="descricao-busca span10">
            <h3><a href="<%= user_profile_path(user.id) %>"><%= user.name %></a></h3>
          </div>
        </div><!--/row-fluid-->
      <% end %>
    </div><!--/resultado-->

  </div><!--/bloco-resultado-busca-->

  <div class="bloco-resultado-busca">
    <p class="subtitulo-busca">Lojas</p>
    <span class="label label-important"><%= @all_stores.size %></span> Resultados para <strong>"<%= @search %>"</strong>

    <div class="resultado">
      <% @all_stores.each do |store| %>
        <div class="row-fluid">
          <div class="thumb-medio span2">
            <a title="<%= store.name %>" href="#" class="tooltipo" data-placement="top"></a>
            <%= render 'shared/framed_picture-small', image_url: store.image_url %>
          </div>

          <div class="descricao-busca span10">
            <h3><a href="#"><%= store.name %></a></h3>
          </div>
        </div><!--/row-fluid-->
      <% end %>
    </div><!--/resultado-->
  </div><!--/bloco-resultado-busca-->

  <div class="bloco-resultado-busca">
    <p class="subtitulo-busca">Ofertas</p>
    <span class="label label-important"><%= @all_offers.size %></span> Resultados para <strong>"<%= @search %>"</strong>

    <div class="resultado">
      <% @all_offers.each do |o| %>
        <div class="row-fluid">
          <div class="thumb-medio-cupom span2">
            <img src="/img/upload/cupom.svg" alt="Cupom">
          </div>

          <div class="descricao-busca span10">
            <h3><a href="#">Oferta de tal</a></h3>
          </div>
        </div><!--/row-fluid-->
      <% end %>
    </div><!--/resultado-->
  </div><!--/bloco-resultado-busca-->
</div><!--/resultado-busca-->