config/routes.rb
PromrWeb::Application.routes.draw do

  devise_scope :users do
    get '/users/sign_in', to: redirect('/'), :as => :new_user_session
  end

  devise_for :users,
             controllers: { :omniauth_callbacks => "users/omniauth_callbacks" },
             skip: [:registrations, :passwords, :unlocks]

  controller :home do
    get '/home', action: :index
    get '/contact_us', action: :contact_us, as: :contact_us
    get '/terms', action: :terms, as: :terms
  end

  unauthenticated :user do
    root to: redirect('/home')
  end

  authenticated :user do
    root controller: :user_dashboard, action: :promr_box
  end

  controller :user_dashboard do
    get '/search', action: :search, as: :search
    get '/friends', action: :friends, as: :friends
    get '/facebook_friends', action: :facebook_friends, as: :facebook_friends
  end

  controller :user_profile do
    get '/me/edit', action: :edit, as: :edit_user_profile
    put '/me', action: :update, as: :update_user_profile
    get '/me', action: :show_me, as: :my_profile

    get '/u/:id', action: :show, as: :user_profile

    get '/u/:id/invite_friend', action: :invite_friend, as: :invite_friend
    get '/u/:id/approve_friend', action: :approve_friend, as: :approve_friend
    get '/u/:id/cancel_invite', action: :cancel_invite, as: :cancel_invite
    get '/u/:id/remove_friend', action: :remove_friend, as: :remove_friend
    get '/u/:id/block_friend', action: :block_friend, as: :block_friend
    get '/u/:id/unblock_friend', action: :unblock_friend, as: :unblock_friend
  end

  resources :coupons, only: [:index, :show]

  resources :stores, only: [:index]

  resources :offers, only: [:show] do
    put 'new_coupon', action: :new_coupon, as: :new_coupon
  end

  devise_for :store_users

  get '/store_dashboard', action: :index, controller: :store_dashboard, as: :store_user_root

  namespace :store_dashboard do
    post '/change_image', action: :change_image
    resources :offers do
      get '/activate', action: :activate
      get '/deactivate', action: :deactivate
    end
    resources :coupons do
      get '/buy', action: :buy, :on => :collection
    end

    post '/use_coupon', action: :use_coupon
    get '/use_coupon' => redirect('/store_dashboard/')
    get '/profile', action: :profile
    get '/help', action: :profile
  end

  devise_for :admin_users

  get '/admin_dashboard', action: :index, controller: :admin_dashboard, as: :admin_user_root

  namespace :admin_dashboard do
    resources :stores
    resources :offers
    resources :store_users
  end

end

app/controllers/user_profile_controller.rb
class UserProfileController < ApplicationController
  include UserDashboardControllersSharedBehavior

  def show_me
    @user = current_user
    render :show
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user

    if @user.update_profile_attributes(params[:user])
      notices << 'Seus dados foram salvos com sucesso!'
      sign_in(@user, bypass: true)
    else
      add_errors_for @user
    end
    render action: :edit
  end

  def invite_friend
    @friend = User.find(params[:id])
    current_user.invite(@friend)
    notices << "Aguarde aprovacao do usuario #{@friend.name}."
    redirect_to(:back)
  end

  def cancel_invite
    @friend = User.find(params[:id])
    current_user.remove_friendship(@friend)
    notices << "A solicitacao de amizade com #{@friend.name} foi cancelada."
    redirect_to(:back)
  end

  def approve_friend
    @friend = User.find(params[:id])
    current_user.approve(@friend)
    notices << "Voce e #{@friend.name} agora sao amigos!"
    redirect_to(:back)
  end

  def remove_friend
    @friend = User.find(params[:id])
    current_user.remove_friendship(@friend)
    notices << "Voce e #{@friend.name} nao sao mais amigos."
    redirect_to(:back)
  end

  def block_friend
    @friend = User.find(params[:id])
    current_user.block(@friend)
    notices << "Voce bloqueou #{@friend.name}."
    redirect_to(:back)
  end

  def unblock_friend
    @friend = User.find(params[:id])
    current_user.unblock(@friend)
    notices << "Voce desbloqueou a amizade com #{@friend.name}."
    redirect_to(:back)
  end
end

app/views/user_profile/edit.html.erb
<h1>Editar Perfil</h1>

<%= render 'shared/messages' %>
<%= form_for @user, as: :user, url: update_user_profile_path, method: 'put', id: 'profile-edit-form' do |f| %>
  <fieldset>

    <legend>Dados pessoais</legend>
    <div class="controls">
      <%= f.label :name %>
      <%= f.text_field :name, id: 'user_name', class: 'span6', placeholder: 'Francisco Marley Dieb' %>
    </div>

    <div class="controls controls-row">
      <% if false %>
      <div class="span3">
        <%= f.label :cpf %>
        <%= f.text_field :cpf, id: 'user_cpf', class: 'span12',
            pattern: '\d{3}\.\d{3}\.\d{3}-\d{2}', placeholder: '000.000.000-00' %>
      </div>
      <% end %>

      <div class="span4">
        <%= f.label :email %>
        <%= f.email_field :email, id: 'user_email', class: 'span12', placeholder: 'marley@gmail.com' %>
      </div>

      <div class="span2" id="container_birthdate">
        <%= f.label :birthdate %>
        <div id="div_birthdate" class='input-append date span9'>
          <%= f.text_field :birthdate, id: 'user_birthdate', class: 'span12' %>
          <span class='add-on'><i data-time-icon='icon-calendar'></i></span>
        </div>
      </div>
    </div>
  </fieldset>

  <% if false %>
    <fieldset>
      <legend>Alteração de senha</legend>

      <p><small>* Só preencha os campos abaixo se quiser alterar sua senha</small></p>

      <%= f.label :current_password %>
      <%= f.password_field :current_password, id: 'user_current_password' %>

      <%= f.label :password %>
      <%= f.password_field :password, id: 'user_password' %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation,  id: 'user_password_confirmation' %>
    </fieldset>
  <% end %>

  <div class="controls controls-row">
    <p><a href="#">Leia os nossos termos de serviço.</a></p>
    <p><a href="#">Saiba mais sobre a sua privacidade.</a></p>

    <button type="submit" class="btn btn-success"><i class="icon-ok icon-white"></i>&nbsp;Salvar</button>

    <a href="#" class="btn btn-danger"><i class="icon-remove icon-white"></i>&nbsp;Cancelar</a>
  </div>
<% end %>

<script type='text/javascript'>
  var birthdate_empty = <%= @user.birthdate.blank? %>;
  $('#div_birthdate').datetimepicker(Promr.BOOTSTRAP_DATE_PICKER_FORMAT);
  if (birthdate_empty) {
    $('#container_birthdate')
      .popover({
        placement : 'right',
        html: 'true',
        content: 'Preenchendo sua data de nascimento você tem acesso a ofertas especiais'
      })
      .popover('show')
      .on('click', function() { $(this).popover('destroy') });
  }
</script>

app/views/user_profile/show.html.erb
<h1>Perfil Público</h1>

<div class="row-fluid">
  <div class="photo-phrame">
    <%= render 'shared/framed_picture-medium', image_url: @user.image_url %>
  </div>

  <div>
    <p class="nome titulo-box"><%= @user.name %></p>
    <p>
      <span><strong>Pontos:&nbsp;</strong></span><span class="badge">430 / 500</span>
      <span><strong>Nível:&nbsp;</strong></span><span class="badge">3</span>
    </p>

    <div id="karma" class="progress active progress-success">
      <div class="bar" style="width: 80%"></div>
    </div>
  </div>
</div><!--/row-fluid-->

<div id="botoes-add">
  <% if current_user.allow_invite?(@user) %>
    <a href="<%= invite_friend_path(@user.id) %> "class="btn btn-danger">
      <i class="icon-plus icon-white"></i> Adicionar
    </a>
  <% end %>
  <% if current_user.allow_cancel_invite?(@user) %>
    <a href="<%= cancel_invite_path(@user.id) %> "class="btn btn-warning">
       <i class="icon-remove icon-white"></i> Cancelar solicitacao de amizade
    </a>
  <% end %>
  <% if current_user.friend_with?(@user) %>
    <a href="<%= remove_friend_path(@user.id) %> "class="btn btn-success">
       <i class="icon-remove icon-white"></i> Desfazer amizade
    </a>
    <a href="<%= block_friend_path(@user.id) %> "class="btn btn-inverse">
       <i class="icon-ban-circle icon-white"></i> Bloquear amigo
    </a>
  <% end %>
  <% if current_user.blocked?(@user) %>
    <a href="<%= unblock_friend_path(@user.id) %> "class="btn btn-danger">
       <i class="icon-thumbs-up icon-white"></i> Desbloquear amigo
    </a>
  <% end %>
</div><!--/botoes-add-->

<fieldset>
  <legend>Lojas que ele(a) curte</legend>
  <div id="thumbs-lojas">
    <% @user.following_stores.each do |store| %>
      <div class="logo-loja">
        <a href="#">
          <img src="<%= store.image_url %>" alt="Logo da Loja" title="Loja"/>
        </a>
      </div>
    <% end %>
  </div>
</fieldset>